module.exports = {
    pluginName: "homebridge-hubitat-tonesto7",
    platformDesc: "Hubitat",
    platformName: "Hubitat-v2",
    pluginVersion: require("../../package.json").version,
    packageFile: require("../../package.json"),
    knownCapabilities: [
        // "Acceleration Sensor",
        "AccelerationSensor",
        "Actuator",
        "AirQuality",
        "Alarm System Status",
        "Alarm",
        "AlarmSystemStatus",
        "Audio Mute",
        "Audio Volume",
        "Battery",
        "Bulb",
        "Button",
        "CarbonDioxideMeasurement",
        "CarbonMonoxideDetector",
        "ColorControl",
        "ColorTemperature",
        "Configuration",
        "ContactSensor",
        "Door",
        "DoorControl",
        "DoubleTapableButton",
        "EnergyMeter",
        "Fan",
        "FanControl",
        // "FanLight",
        "GarageDoorControl",
        "HoldableButton",
        "IlluminanceMeasurement",
        "Light",
        "LightBulb",
        "Lock",
        "LockCodes",
        "Mode",
        "MotionSensor",
        "Piston",
        "Polling",
        "PowerMeter",
        "PowerSource",
        "PresenceSensor",
        "PushableButton",
        "Outlet",
        "Refresh",
        "RelativeHumidityMeasurement",
        // "ReleasableButton",
        "Routine",
        "Sensor",
        "SmokeDetector",
        "Speaker",
        "Switch",
        "SwitchLevel",
        "TamperAlert",
        "TemperatureMeasurement",
        "Thermostat",
        "ThermostatCoolingSetpoint",
        "ThermostatFanMode",
        "ThermostatHeatingSetpoint",
        "ThermostatMode",
        "ThermostatOperatingState",
        "ThermostatSetpoint",
        "Valve",
        "WaterSensor",
        "Window",
        "WindowShade",
    ],
};
